### ISSUE TITLE
[kamunu]

### ISSUE THREAD

**Issue by omazapa** [colav/HunabKu_plugins#40]
improve error control, if a parameter is required as a return.
example: html bad request 400

**Comment by fedevergara** [comment]
Control errors were fixed and the apidoc interface was improved.

**Comment by omazapa** [comment]
Still missing error control with the return is not valid.

**Comment by fedevergara** [comment]
The error with the not valid return parameter where fixed.

**Comment by omazapa** [comment]
where is the PR with the changes?
